### ISSUE TITLE
feature request: Queueing Message

### ISSUE THREAD

**Issue by areisle** [TeamWertarbyte/material-ui-snackbar-provider#10]
Hi I really like this library, but for my usage I'd need a second call to showMessage to transition the first message out before showing the next message.  if you think this sounds like a good idea and need any development support I'm willing to implement it and submit a pull?

**Comment by leMaik** [comment]
I like this idea :+1: Maybe there should be an option to either replace the current message immediately (thus clearing the queue) or to wait for the queue to be emptied.

**Comment by simplenotezy** [comment]
For anyone wanting this as well https://github.com/iamhosseindhv/notistack

**Comment by leMaik** [comment]
People seem to want this, yet after three years, nobody took the time to submit a PR. Personally, I don't need it and if I needed it, I would probably switch to Notistack instead of re-inventing the wheel.
For simple use cases, I still prefer material-ui-snackbar-provider. :)
