### ISSUE TITLE
Custom close icon and message markup

### ISSUE THREAD

**Issue by sgimeno** [TeamWertarbyte/material-ui-snackbar-provider#11]
Hi, I'm trying to use this library to toggle a custom snackbar created following the examples from MaterialUI https://material-ui.com/components/snackbars/#customized-snackbars

In the Provider code the action and the message props are limited to be strings. With the current implementation the only way I see to achieve a similar result would be to pass React components as arguments of _.showMessage_ method ie:
```
...
this.props.snackbar.showMessage(
      'Saved to Library',
      <IconButton
        key="close"
        aria-label="Close"
        color="inherit"
      >
        <CloseIcon />
      </IconButton>, () => this.handleUndo(),
    );
```

<img width="699" alt="Screenshot 2019-10-27 at 22 21 55" src="https://user-images.githubusercontent.com/946661/67642064-599c9780-f908-11e9-97c7-77a381714902.png">

Even if this "works" and places the IconButton it is wrapped by the Button in the provider `<Button color='secondary' ... />` creating not ideal hovers and markup. Also it is a annoying to have to pass that component on every call.  Would it be possible to support both strings and components or component functions to be able to customize the snackbar shown. Or pass an _action_ prop with some initial component and just add an onClick handler to it? Would this be a desired enhancement?

**Comment by leMaik** [comment]
Related to #7, this is possible by using `SnackbarComponent` in v1.4.0, I'll add an example later this week.

**Comment by GeocelinJ** [comment]
@leMaik  , 

>>this is possible by using SnackbarComponent in v1.4.0, I'll add an example later this week.

could you give example to add close icon next to message.

**Comment by leMaik** [comment]
@GeocelinJ Yes, I'll add examples today. See #19 for updates on that.

**Comment by leMaik** [comment]
Done :tada: 
Examples are available [here](https://github.com/TeamWertarbyte/material-ui-snackbar-provider/blob/master/stories/1-custom.stories.js) and can be seen in action [in the storybook](https://teamwertarbyte.github.io/material-ui-snackbar-provider/?path=/story/snackbarprovider--with-custom-snackbar).
