### ISSUE TITLE
Add examples for custom close icons and message variants

### ISSUE THREAD

**Issue by GeocelinJ** [TeamWertarbyte/material-ui-snackbar-provider#19]
Hello,

is there any way to add close icon with **SnackbarProvider** prop itself, without using showMessage.
If available please provide  the example..

Thanks

**Comment by leMaik** [comment]
Done :tada: 
Examples are available [here](https://github.com/TeamWertarbyte/material-ui-snackbar-provider/blob/master/stories/1-custom.stories.js) and can be seen in action [in the storybook](https://teamwertarbyte.github.io/material-ui-snackbar-provider/?path=/story/snackbarprovider--with-custom-snackbar).
