### ISSUE TITLE
Unknown event handler property `onActionTouchTap`. It will be ignored.

### ISSUE THREAD

**Issue by tomscholz** [TeamWertarbyte/material-ui-snackbar-provider#2]
It looks like `onActionTouchTap` was removed in material-ui < 1.0.0. 
```
Warning: Unknown event handler property `onActionTouchTap`. It will be ignored.
    in div (created by Snackbar)
    in EventListener (created by ClickAwayListener)
    in ClickAwayListener (created by Snackbar)
    in EventListener (created by Snackbar)
    in Snackbar (created by withStyles(Snackbar))
    in withStyles(Snackbar) (created by SnackbarProvider)
    in div (created by SnackbarProvider)
    in SnackbarProvider (created by App)
    in App (created by ReactMeteorDataComponent)
    in ReactMeteorDataComponent
    in MuiThemeProvider (created by MuiThemeProviderWrapper)
    in MuiThemeProviderWrapper
```

**Comment by leMaik** [comment]
It's still being used: https://github.com/callemall/material-ui/blob/master/src/Snackbar/Snackbar.js#L78

**Comment by tomscholz** [comment]
You are looking at `v0.19.4`. It's gone in version 1. Have a look at the `v1-beta` branch. :)

**Comment by leMaik** [comment]
> It looks like onActionTouchTap was removed in material-ui < 1.0.0.

So you mean ">= 1.0.0"? :wink: This component is not yet compatible with material-ui 1.0.0, but we're working on that

**Comment by tomscholz** [comment]
Yes ^^. Even though I can confirm that this is working with v1 except for the error above :)

**Comment by tomscholz** [comment]
What about creating a `v1-support` branch, where we can work on support for v1?

**Comment by leMaik** [comment]
…and 100% test coverage, yes :+1: That's what we do for all our material-ui components. I'll look into porting this component later / this week end.

**Comment by leMaik** [comment]
@tomscholz Done :tada: `npm i --save material-ui-snackbar-provider@next`

**Comment by devuxer** [comment]
Any plans to update @types/material-ui to replace `onActionTouchTap` with `onActionClick`?

Here is the offending file: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/material-ui/index.d.ts

**Comment by leMaik** [comment]
@devuxer Yes, it was changed in v0.20 :roll_eyes: I don't really get why there are still breaking changes in the legacy version. I'll fix it asap.

**Comment by devuxer** [comment]
@leMaik, Thank you! I attempted a pull request for this:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22026

Sorry for neglecting to paste a link sooner.

**Comment by leMaik** [comment]
@devuxer Would you like to PR here? :+1:

**Comment by devuxer** [comment]
@leMaik , I'm not sure I understand your question. Are you saying I put my PR in the wrong project?

**Comment by leMaik** [comment]
@devuxer You fixed the typings, which is nice. :wink: However, the attribute also needs to be changed here. I'll fix it, that's simpler than explaining it.
