### ISSUE TITLE
customParameters is not used

### ISSUE THREAD

**Issue by jmoore315** [TeamWertarbyte/material-ui-snackbar-provider#20]
looks like `customParameters` never gets passed along to the material-ui snackbar component

See https://github.com/TeamWertarbyte/material-ui-snackbar-provider/blob/b0f75e5b9d051c831b925d2a68d950188abb7581/src/SnackbarProvider.js#L8

**Comment by leMaik** [comment]
Indeed, it's not used by the default snackbar renderer. To see how it can be used, take a look at this example: https://github.com/TeamWertarbyte/material-ui-snackbar-provider/tree/master/stories/CustomSnackbar
