### ISSUE TITLE
The custom snack bar is overriding material-ui theme palette colors.

### ISSUE THREAD

**Issue by AleDaraio** [TeamWertarbyte/material-ui-snackbar-provider#21]
Scenario:
I'm using the customSnackBar with the colored Alerts, the same way the example in the repo.
Also, I'm using a custom material-ui theme, changing the primary and secondary colors.
`  palette: {
    primary: {
      main: primaryColor,
    },
    secondary: {
      main: secondaryColor,
    },
  },`

When the snack bar is visible, both colors are being overridden with the Material-ui default colors, primaryColor change to blue, and secondary color change to red.
When transition finish, all colors come back to normal

For example, the mail icon is set with the primary color and the notification icon with the secondary color.

![Screen Recording 2020-07-02 at 14 29 10](https://user-images.githubusercontent.com/1211222/86391948-fcb06880-bc70-11ea-8369-5d84f065a4d6.gif)

**Comment by leMaik** [comment]
I don't see how our code changes the theme colors. 🤔

**Comment by AleDaraio** [comment]
You are totally right. 
The snack bar is working perfectly.
Closing the issue, because it was not.
Thanks!!!

**Comment by AleDaraio** [comment]
Closing the issue.
