### ISSUE TITLE
How to override autoHideDuration for specific message

### ISSUE THREAD

**Issue by ArnaudPel** [TeamWertarbyte/material-ui-snackbar-provider#38]
From the readme, I cannot find out how to pass `autoHideDuration` to a single message. I tried the following,

```js
snackbar.showMessage('text', undefined, undefined, {autoHideDuration: 10000});
```

But the snackbar is hidden after 1.5 seconds, which is the value I passed to `<SnackbarProvider>`.

Many thanks

**Comment by leMaik** [comment]
After using this library for years, I had just encountered this issue a few weeks ago, too. Fix is in [v1.6.0](https://github.com/TeamWertarbyte/material-ui-snackbar-provider/releases/tag/v1.6.0) and (if you're using mui v5) in the upcoming v2.0.0.
