### ISSUE TITLE
Support material-ui v1

### ISSUE THREAD

**Issue by nosovsh** [TeamWertarbyte/material-ui-snackbar-provider#4]

**Comment by tomscholz** [comment]
Have a look at the [`next`](https://github.com/TeamWertarbyte/material-ui-snackbar-provider/tree/next) branch. Please close...

**Comment by nosovsh** [comment]
Thanks! created PR https://github.com/TeamWertarbyte/material-ui-snackbar-provider/pull/5 for readme update
