### ISSUE TITLE
Handling message "variants"

### ISSUE THREAD

**Issue by Vincz** [TeamWertarbyte/material-ui-snackbar-provider#7]
Hi! First of all, nice plugin :)
I was wondering if you have plan to handle "variant" on message for success, error, warning, info, ....

Something like:

```
this.props.snackbar.showMessage('you did good!', 'success', 'Undo', () => this.handleUndo())

this.props.snackbar.showMessage('Doh! Something really bad...', 'error', 'Undo', () => this.handleUndo())
```

We could have default variants on the provider and we could override or add different styles for each variants. 

What do you think?

**Comment by leMaik** [comment]
Good idea. I wouldn't add a `variant` parameter but instead allow an object to be passed as `message` and allow the user to provide a custom `SnackBarRenderer` prop on the `SnackBarProvider` that can then handle custom messages.

I think that this approach would be way more flexible.

**Comment by jpca999** [comment]
any update on this ?  OR any other github repo where i can use the snackbkar success message via the provider ?

**Comment by leMaik** [comment]
@jpca999 This is now possible by using `SnackbarComponent` in v1.4.0. I'll publish an example that uses Material-UI's `Alert` component (currently in the lab) later this week.

**Comment by doctorallen** [comment]
@leMaik any chance you have that example using the Alert component, this is exactly what I'm looking for. Thanks.

**Comment by leMaik** [comment]
@doctorallen Sorry, I'll add one today. I implemented exactly what you need two weeks ago, I just have to tidy it up for an example. See #19 for updates on that.

**Comment by leMaik** [comment]
Done :tada: 
Examples are available [here](https://github.com/TeamWertarbyte/material-ui-snackbar-provider/blob/master/stories/1-custom.stories.js) and can be seen in action [in the storybook](https://teamwertarbyte.github.io/material-ui-snackbar-provider/?path=/story/snackbarprovider--with-custom-snackbar).

**Comment by doctorallen** [comment]
great, thanks @leMaik !

**Comment by devpascoe** [comment]
Thanks for the code example. When using typescript it looks like we might need to expose SnackbarComponent in the type definition in SnackbarProvider. IDE complaining about SnackbarComponent not being an overloaded type.
